# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

# Create a bunch of minerals and metals
Commodity.create(name: 'Aluminium',   category: "metals",   galactic_average: 412   )
Commodity.create(name: 'Bauxite',     category: "minerals", galactic_average: 216   )
Commodity.create(name: 'Bertrandite', category: "minerals", galactic_average: 2694  )
Commodity.create(name: 'Beryllium',   category: "metals",   galactic_average: 8549  )
Commodity.create(name: 'Bismuth',     category: "metals",   galactic_average: 2531  )
Commodity.create(name: 'Cobalt',      category: "metals",   galactic_average: 823   )
Commodity.create(name: 'Coltan',      category: "minerals", galactic_average: 1550  )
Commodity.create(name: 'Copper',      category: "metals",   galactic_average: 570   )
Commodity.create(name: 'Cryolite',    category: "minerals", galactic_average: 2378  )
Commodity.create(name: 'Gallite',     category: "minerals", galactic_average: 2101  )
Commodity.create(name: 'Gallium',     category: "metals",   galactic_average: 5426  )
Commodity.create(name: 'Goslarite',   category: "minerals", galactic_average: 972   )
Commodity.create(name: 'Gold',        category: "metals",   galactic_average: 9742  )
Commodity.create(name: 'Hafnium 178', category: "metals",   galactic_average: 66000 )
Commodity.create(name: 'Indite',      category: "minerals", galactic_average: 2378  )
Commodity.create(name: 'Indium',      category: "metals",   galactic_average: 6175  )
Commodity.create(name: 'Jadeite',     category: "minerals", galactic_average: 12666 )
Commodity.create(name: 'Lanthanum',   category: "metals",   galactic_average: 9125  )
Commodity.create(name: 'Lepidolite',  category: "minerals", galactic_average: 600   )
Commodity.create(name: 'Lithium',     category: "metals",   galactic_average: 1749  )
Commodity.create(name: 'Moissanite',  category: "minerals", galactic_average: 7503  )
Commodity.create(name: 'Osmium',      category: "metals",   galactic_average: 7031  )
Commodity.create(name: 'Painite',     category: "minerals", galactic_average: 33000 )
Commodity.create(name: 'Palladium',   category: "metals",   galactic_average: 13527 )
Commodity.create(name: 'Platinum',    category: "metals",   galactic_average: 18814 )
Commodity.create(name: 'Pyrophyllite',category: "minerals", galactic_average: 1646  )
Commodity.create(name: 'Rutile',      category: "minerals", galactic_average: 412   )
Commodity.create(name: 'Silver',      category: "metals",   galactic_average: 5088  )
Commodity.create(name: 'Taaffeite',   category: "minerals", galactic_average: 20077 )
Commodity.create(name: 'Tantalum',    category: "metals",   galactic_average: 4196  )
Commodity.create(name: 'Thalium',     category: "metals",   galactic_average: 3973  )
Commodity.create(name: 'Thorium',     category: "metals",   galactic_average: 11860 )
Commodity.create(name: 'Titanium',    category: "metals",   galactic_average: 1154  )
Commodity.create(name: 'Uranium',     category: "metals",   galactic_average: 2869  )
Commodity.create(name: 'Urannite',    category: "minerals", galactic_average: 1029  )

guathiti = System.create(name: 'Guathiti')
SystemObject.create(name: 'Guathiti 6', system: guathiti,   object_type: 'planet')
SystemObject.create(name: 'Messier Port', system: guathiti, object_type: 'station')
